config/routes.rb
Gripebox::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages

  match '/flag-gripe' => 'flag_gripes#update'

  match '/embed_details' => 'embed_details#create'

  match '/error/404' => 'error_pages#index'

  match '/facebook/access_token' => 'account#facebook'

  match 'filter_gripe_view' => 'home#filter_gripe_view'
  
  match 'show-more' => 'show_more#index'
  match 'show-more-view-all' => 'show_more#view_all'

  match 'check-gripes' => 'show_more#check_gripes'
  match 'check-gripes-view-all' => 'show_more#check_gripes_view_all'

  match 'gripe_view' => 'home#gripe_view'

  match 'check_read' => 'notifications#check_read'

  match 'check_user_reg_param' => 'home#check_user_reg_param'

  match 'check_user_login_param' => 'home#check_user_login_param'
  
  match '/account/tw' => 'account#tw'

  match '/account/fb' => 'account#fb'

  match 'account/avatar/upload' => 'account#avatar_upload'

  match 'account/avatar' => 'account#avatar'

  match 'count_tags' => 'home#count_tags'

  match 'check_embed_image' => 'uploader#check_embed_image'

  match 'account/remove' => 'account#remove'

  match 'account/email_me' => 'account#email_me'

  match 'uploader' => 'uploader#index'

  match 'gripe/power' => 'gripes#power'
  
  match 'file_uploads' => 'uploader#index'

  match 'uploader/image' => 'uploader#image'

  match 'search' => 'search#index'

  match 'subscriptions' => 'subscriptions#index'

  match 'notifications' => 'notifications#index'

  match '/gripe/rate' => 'gripes#rate'

  match '/gripe/image/update' => 'gripes#image_update'

  match '/gripe/video/update' => 'gripes#video_update'  

  match '/gripe/embed/save' => 'gripes#embed_save'

  match '/gripe/update/text' => 'gripes#text_update'  

  match '/gripe/filter' => 'gripes#filter'  

  match '/gripe/comment' => 'gripes#comment'

  match '/gripe/subscription' => 'gripes#subscription'  

  match '/mygripes' => 'gripes#mygripes'  

  resources :gripes

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match 'account' => 'account#index'

  match 'account/password' => 'account#password'

  match '/account/setting/save' => 'account#setting_save'
  
  match '/auth/:provider/callback' => 'authentications#create'

  resources :authentications

  devise_for :users, :controllers => { :registrations => 'registrations' }

  root :to => 'home#index'

end

app/views/notifier/send_activity_my.html.erb
<div class="main" style="width: 960px; margin: 20px; font-family: Arial;">
  <img src="<%= url_for(root_url.to_s + "assets/mail.png") %>" alt="Header image">

  <h2 style="font-size: 24px; padding: 20px 0 20px 20px; color: #4c4c4c; font-family: Arial; margin:0">Hi, <%= @user.username %>!</h2>


  <div class="info" style="padding: 0 40px 0 20px; font-family: Arial;">
   <h4 style=" color: #999999;font-weight: normal;font-size: 19px;padding: 0 0 5px 0;margin: 0 0 8px 0;border-bottom: 1px solid #ccc;font-style: italic; font-family: Arial;" >Activity in my gripes:</h4>
   <p>
     <ul id="" class="">
      <% @msg.each do |msg| %>
        <li>
          <%= msg.activity.created_at.strftime("%m/%d/%y") %>: <%= msg.activity.what %> in <%= link_to msg.activity.gripe.title, gripes_url(:id => msg.activity.gripe.id) %>
        </li>
      <% end %>  
      
     </ul><!-- / -->
   </p>

   <p style="color: #b2b2b2; padding: 0 0 10px 0;font-size: 14px; margin:0; font-family: Arial;">
    If you received this message in error and did not sign up for a Gripebox account, click 
    <a href="<%= url_for(root_url.to_s) %>" style="color: #68bede; font-family: Arial;">not my account.</a>
   </p>
   <p style="color: #b2b2b2; padding: 0 0 10px 0;font-size: 14px; margin:0; font-family: Arial;">
    Please do not reply to this message; it was sent from an unmonitored email address.  This message is a service email related to your use of Gripebox.  For general inquiries or to request support with your Gripebox account, please visit us at <a href="<%= url_for(root_url.to_s) %>" style="color: #68bede; font-family: Arial;">Gripebox Support.</a>

   </p>
  </div>
</div>

app/views/notifier/send_activity_sub.html.erb
<div class="main" style="width: 960px; margin: 20px; font-family: Arial;">
  <img src="<%= url_for(root_url.to_s + "assets/mail.png") %>" alt="Header image">

  <h2 style="font-size: 24px; padding: 20px 0 20px 20px; color: #4c4c4c; font-family: Arial; margin:0">Hi, <%= @user.username %>!</h2>


  <div class="info" style="padding: 0 40px 0 20px; font-family: Arial;">
   <h4 style=" color: #999999;font-weight: normal;font-size: 19px;padding: 0 0 5px 0;margin: 0 0 8px 0;border-bottom: 1px solid #ccc;font-style: italic; font-family: Arial;" >Activity in subscription gripes:</h4>
   <p>
     <ul id="" class="">
      <% @msg.each do |msg| %>
        <li>
          <%= msg.activity.created_at.strftime("%m/%d/%y") %>: <%= msg.activity.what %> in <%= link_to msg.activity.gripe.title, gripes_url(:id => msg.activity.gripe.id) %>
        </li>
      <% end %>  
      
     </ul><!-- / -->
   </p>

   <p style="color: #b2b2b2; padding: 0 0 10px 0;font-size: 14px; margin:0; font-family: Arial;">
    If you received this message in error and did not sign up for a Gripebox account, click 
    <a href="<%= url_for(root_url.to_s) %>" style="color: #68bede; font-family: Arial;">not my account.</a>
   </p>
   <p style="color: #b2b2b2; padding: 0 0 10px 0;font-size: 14px; margin:0; font-family: Arial;">
    Please do not reply to this message; it was sent from an unmonitored email address.  This message is a service email related to your use of Gripebox.  For general inquiries or to request support with your Gripebox account, please visit us at <a href="<%= url_for(root_url.to_s) %>" style="color: #68bede; font-family: Arial;">Gripebox Support.</a>

   </p>
  </div>
</div>

app/views/notifier/send_activity_top.html.erb
<div class="main" style="width: 960px; margin: 20px; font-family: Arial;">
  <img src="<%= url_for(root_url.to_s + "assets/mail.png") %>" alt="Header image">

  <h2 style="font-size: 24px; padding: 20px 0 20px 20px; color: #4c4c4c; font-family: Arial; margin:0">Hi, <%= @user.username %>!</h2>


  <div class="info" style="padding: 0 40px 0 20px; font-family: Arial;">
   <h4 style=" color: #999999;font-weight: normal;font-size: 19px;padding: 0 0 5px 0;margin: 0 0 8px 0;border-bottom: 1px solid #ccc;font-style: italic; font-family: Arial;" >Top week 3 gripes:</h4>
   <p>
     <ul id="" class="">
      <% @buzz.each do |buzz| %>
        <li>
          <%= link_to buzz.tag, search_url(:"search-keywords" => buzz.tag) %>
        </li>
      <% end %>  
      
     </ul><!-- / -->
   </p>

   <p style="color: #b2b2b2; padding: 0 0 10px 0;font-size: 14px; margin:0; font-family: Arial;">
    If you received this message in error and did not sign up for a Gripebox account, click 
    <a href="<%= url_for(root_url.to_s) %>" style="color: #68bede; font-family: Arial;">not my account.</a>
   </p>
   <p style="color: #b2b2b2; padding: 0 0 10px 0;font-size: 14px; margin:0; font-family: Arial;">
    Please do not reply to this message; it was sent from an unmonitored email address.  This message is a service email related to your use of Gripebox.  For general inquiries or to request support with your Gripebox account, please visit us at <a href="<%= url_for(root_url.to_s) %>" style="color: #68bede; font-family: Arial;">Gripebox Support.</a>

   </p>
  </div>
</div>